"""
heatmap_service.py
==================
Top-level facade for heatmap results.

Reads the heatmap data produced by services/cv/video_processor.py and
converts it into the HeatmapData schema the routes expect.

Changes in this revision
------------------------
* team_a_heatmap_url now resolves from ProcessingOutput.heatmap_team1_path
  (per-team heatmap generated by _generate_per_team_heatmaps).
* team_b_heatmap_url now resolves from ProcessingOutput.heatmap_team2_path.
* The combined all-player heatmap is retained as ball_heatmap_url for
  backward compatibility (schema field is reused as "overall activity").
* _path_to_url unchanged — still resolves against RESULTS_DIR as an
  absolute Path to produce /results/... static URLs.
"""

import logging
from pathlib import Path

from config import RESULTS_DIR
from models.schemas import HeatmapData, AnalysisStatus

log = logging.getLogger(__name__)


def _generate_placeholder_matrix(rows: int = 10, cols: int = 15) -> list[list[float]]:
    """Return a zeroed heatmap matrix used when no real CV data is available."""
    return [[0.0] * cols for _ in range(rows)]


def _path_to_url(path: str | None) -> str | None:
    """
    Convert an absolute or relative filesystem path inside the results/
    directory to a URL that FastAPI's StaticFiles mount will serve.

    Handles both:
      - Absolute paths:  /abs/path/to/results/abc/heatmap.jpg  → /results/abc/heatmap.jpg
      - Relative paths:  results/abc/heatmap.jpg               → /results/abc/heatmap.jpg
    """
    if not path:
        return None

    p = Path(path).resolve()
    results_abs = Path(RESULTS_DIR).resolve()

    try:
        rel = p.relative_to(results_abs)
        return f"/results/{rel}"
    except ValueError:
        pass

    # Fallback: try treating path as relative to current working directory
    p_rel = Path(path)
    try:
        rel = p_rel.relative_to(Path("results"))
        return f"/results/{rel}"
    except ValueError:
        pass

    # Last resort: return the path as-is so the frontend still gets something
    log.warning("[heatmap_service] Cannot convert path to URL: %s", path)
    return str(path)


def generate_heatmap(video_id: str, tracking_result) -> HeatmapData:
    """
    Return HeatmapData populated from real CV output (if available)
    or a zeroed placeholder matrix.

    Reads cv_out from tracking_result._cv_output, which analysis.py sets
    before calling this function.

    URL mapping
    -----------
    team_a_heatmap_url  ← ProcessingOutput.heatmap_team1_path  (Team 1 per-team heatmap)
    team_b_heatmap_url  ← ProcessingOutput.heatmap_team2_path  (Team 2 per-team heatmap)
    ball_heatmap_url    ← ProcessingOutput.heatmap_player_path (combined all-player heatmap)
    """
    cv_out = getattr(tracking_result, "_cv_output", None)

    heatmap_matrix   = None
    team1_hm_path    = None
    team2_hm_path    = None
    combined_hm_path = None

    if cv_out is not None and getattr(cv_out, "used_real_model", False):
        heatmap_matrix = getattr(cv_out, "heatmap_matrix", None)

        # Per-team heatmaps (new fields from updated video_processor)
        team1_hm_path = getattr(cv_out, "heatmap_team1_path", None)
        team2_hm_path = getattr(cv_out, "heatmap_team2_path", None)

        # Combined heatmap (existing field — kept as overall activity indicator)
        combined_hm_path = (
            getattr(cv_out, "heatmap_player_path",  None)
            or getattr(cv_out, "heatmap_players_path", None)
        )

        log.debug(
            "[heatmap_service] raw team1=%s  team2=%s  combined=%s",
            team1_hm_path, team2_hm_path, combined_hm_path,
        )

    if heatmap_matrix is None:
        heatmap_matrix = _generate_placeholder_matrix()

    team_a_url   = _path_to_url(team1_hm_path)
    team_b_url   = _path_to_url(team2_hm_path)
    combined_url = _path_to_url(combined_hm_path)

    log.info(
        "[heatmap_service] video_id=%s  team_a_url=%s  team_b_url=%s  combined_url=%s",
        video_id, team_a_url, team_b_url, combined_url,
    )

    return HeatmapData(
        video_id=video_id,
        team_a_heatmap_url=team_a_url,
        team_b_heatmap_url=team_b_url,
        ball_heatmap_url=combined_url,
        heatmap_matrix=heatmap_matrix,
        status=AnalysisStatus.COMPLETED,
    )